server:
  port: 8082

spring:
  applicaiton:
    name: spring-cloud-commons

    
eureka:
  instance:
    instance-id: spring-cloud-commons
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka